### PR TITLE
add eslint ignore file

### PR DESCRIPTION
**Pull request by nikrb**
we don't want to lint the node_modules directory

### CODE REVIEW

**Comment by g1st** [comment]
On my end its not linting node_modules even without this rule or I am missing something?

**Review by g1st — APPROVED** [review]

**Review by zurda — APPROVED** [review]
LGTM, thanks @nikrb !

**Comment by nikrb** [comment]
@g1st ah really? intially I just ran the linter but it took forever, so I *assumed* it was going through node_modules. if you just type `npm run lint` how long does it take for you?

**Comment by g1st** [comment]
@nikrb it takes roughly 5-6 seconds and on current develop branch finds 435 problems.

**Comment by nikrb** [comment]
ok my bad I'll delete this.
it takes 50 seconds on my machine with and without eslintignore ... I knew it was slow but geez :cry:

**Pull request closed without merging**
