### PR TITLE
Fixing linting errors on works page

### PR DESCRIPTION
**Pull request by g1st**
I hope @nikrb you haven't reached this yet! Changed a bit other files as I thought it was silly to pass stringified data to pages components. Plus renamed few variables for clarity.

I am still not sure if I'm creating pull requests the right way.

### CODE REVIEW

**Comment by nikrb** [comment]
I see a lot of linting errors on pages/index.js and two on pages/_app.js. Are they not part of the pr?

**Comment by g1st** [comment]
Yes they are not part of this PR. Sorry probably I shouldn't have touched anything what's not in works.js.
But I am happy to work on those two on different branch.

**Review by nikrb — APPROVED** [review]
LGTM

**Comment by g1st** [comment]
Ha, because I have modified _app.js a bit and this branch is still not merged, when now I am linting other pages it refers to an old _app.js. May this be a lesson for me.

**Review by zurda — APPROVED** [review]

**Pull request merged**
