### PR TITLE
Update UI when item is not available

### PR DESCRIPTION
**Pull request by g1st**
Just the concept for UI when item is not available for purchase. Styling hopefully will improve later.

### CODE REVIEW

**Review by nikrb — COMMENTED** [review]
LGTM
can you check my merge

**Comment by g1st** [comment]
Nik, I think you were merging to old develop here so I merged into current one plus fixed one error with mutiple classnames for material-ui.

**Comment by g1st** [comment]
I think this should be fine now.

**Review by nikrb — APPROVED** [review]
LGTM

**Pull request merged**
