### PR TITLE
Fixing errors left after linting

### PR DESCRIPTION
**Pull request by g1st**
Plus renamed some variables not to collide or to be more clear.

Here I am battling `no-shadow` eslint errors somewhere along the lines of option 2 in [this](https://stackoverflow.com/a/42337137/5870230) stackowerflow answer by just adding `Redux` to original variable. A bit verbose but for me its fine.

Hopefully no errors apart 24 lint ones left!

### CODE REVIEW

**Comment by g1st** [comment]
My linter showed quite a lot of prettier errors on `care-guide.js`, `commissions.js` and `terms-conditions.js` pages. I think its because of line length rule.
@nikrb, if you would try to run linter now, I am interested how many lint errors would you get, then try to remove character and add it back, save file and check linter again! :)

**Comment by nikrb** [comment]
I have 2 moderate vulnerability warning on install and following linter output:
```
/home/nik/projects/chingu/voyage8/bears14/authentication-server/controllers/authentication.js
  1:21  error  Unable to resolve path to module 'jwt-simple'  import/no-unresolved

/home/nik/projects/chingu/voyage8/bears14/authentication-server/models/User.js
  2:24  error  Unable to resolve path to module 'bcrypt-nodejs'  import/no-unresolved

/home/nik/projects/chingu/voyage8/bears14/authentication-server/router.js
  1:26  error  Unable to resolve path to module 'passport'  import/no-unresolved

/home/nik/projects/chingu/voyage8/bears14/authentication-server/server.js
  6:24  error  Unable to resolve path to module 'morgan'  import/no-unresolved

/home/nik/projects/chingu/voyage8/bears14/authentication-server/services/passport.js
  1:26  error  Unable to resolve path to module 'passport'        import/no-unresolved
  2:29  error  Unable to resolve path to module 'passport-jwt'    import/no-unresolved
  3:32  error  Unable to resolve path to module 'passport-jwt'    import/no-unresolved
  4:31  error  Unable to resolve path to module 'passport-local'  import/no-unresolved

/home/nik/projects/chingu/voyage8/bears14/lib/with-redux-store.js
  45:48  error  'initialReduxState' is missing in props validation  react/prop-types

✖ 9 problems (9 errors, 0 warnings)
```
Are the unresolved modules an oversight?
Also prettier and redux-devtools are added to my package.json on install.

**Comment by g1st** [comment]
Thanks for spotting those moderate vulnerability warnings! Just `npm audit fix` should fix it and we are good here, right?
Linter output is strange though, I'm not getting any linter errors from `authentication-server` apart the very last one `45:48  error  'initialReduxState' is missing in props validation  react/prop-types` which I am not sure how to solve or if we could just disable that rule there.
And prettier with redux-devtools was there in dev dependencies all the time, no? They are there on `master` already.

**Comment by nikrb** [comment]
@g1st npm audit fix will hopefully do the trick.
I saw the linter errors after I removed node_modules and package-lock.json and did an npm install. So possibly you have those packages installed previously?
Yeah the last one, updating package.json is a new one on me, will have to look into that.

**Comment by nikrb** [comment]
re initialReduxState just add it to prop types, e.g.
```
...
import PropTypes from 'prop-types';
...
class ...
  static propTypes = { initialReduxState: PropTypes.object };
...
```

**Comment by g1st** [comment]
@nikrb Thanks for showing ES7 way to declare proptypes! It fixed the last linter error for me! :tada: 
And those unresolved errors which you got left, I think you just forgot to go to `authentication-server/` and run `npm install` there as well!

**Comment by g1st** [comment]
Ok seriously I should stop pushing to this branch! Please review when you will have time and hopefully we can merge this!

**Comment by nikrb** [comment]
re auth server - can we not move the auth package/node_modules to the root directory?
I'll approve this and merge so you can continue your adventure ;)

**Review by nikrb — APPROVED** [review]
LGTM

**Pull request merged**
